"""add notifications table

Revision ID: 483ae2f6da4a
Revises: 8fa53eaab988
Create Date: 2026-02-27 18:01:10.443628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483ae2f6da4a'
down_revision = '8fa53eaab988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('destinataire_type', sa.String(length=20), nullable=False),
    sa.Column('destinataire_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('lue', sa.Boolean(), nullable=False),
    sa.Column('entite_id', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_destinataire_id'), ['destinataire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_destinataire_type'), ['destinataire_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_lue'), ['lue'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_lue'))
        batch_op.drop_index(batch_op.f('ix_notifications_destinataire_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_destinataire_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
