"""initial

Revision ID: 8fa53eaab988
Revises: 
Create Date: 2026-02-27 16:21:32.605745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa53eaab988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comptes_entreprises',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('denomination', sa.String(length=255), nullable=False),
    sa.Column('numero_cc', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_last_changed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cc')
    )
    with op.batch_alter_table('comptes_entreprises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comptes_entreprises_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'editor', 'reader', name='role_enum'), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('entites_base',
    sa.Column('compte_entreprise_id', sa.String(length=36), nullable=True),
    sa.Column('numero_cc', sa.String(length=50), nullable=False),
    sa.Column('denomination', sa.String(length=255), nullable=False),
    sa.Column('forme_juridique', sa.String(length=100), nullable=True),
    sa.Column('secteur_activite', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('origine_saisie', sa.Enum('auto_recensement', 'saisie_artci', 'rapprochement', name='origine_saisie_enum'), nullable=False),
    sa.Column('publie_sur_carte', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compte_entreprise_id'], ['comptes_entreprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cc')
    )
    with op.batch_alter_table('entites_base', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entites_base_compte_entreprise_id'), ['compte_entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entites_base_denomination'), ['denomination'], unique=False)
        batch_op.create_index(batch_op.f('ix_entites_base_publie_sur_carte'), ['publie_sur_carte'], unique=False)
        batch_op.create_index(batch_op.f('ix_entites_base_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_entites_base_secteur_activite'), ['secteur_activite'], unique=False)
        batch_op.create_index(batch_op.f('ix_entites_base_ville'), ['ville'], unique=False)

    op.create_table('otp_codes',
    sa.Column('compte_entreprise_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('type', sa.Enum('inscription', 'connexion', 'reset_password', name='type_otp_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['compte_entreprise_id'], ['comptes_entreprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_compte_entreprise_id'), ['compte_entreprise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index('ix_otp_compte_type_used', ['compte_entreprise_id', 'type', 'used'], unique=False)

    op.create_table('assignations_demandes',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('date_assignation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('echeance', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('en_cours', 'traite_attente_validation', 'valide', 'en_retard', name='statut_assignation_enum'), nullable=False),
    sa.Column('traite_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valide_par', sa.String(length=36), nullable=True),
    sa.Column('valide_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignations_demandes', schema=None) as batch_op:
        batch_op.create_index('ix_assign_agent_statut', ['agent_id', 'statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignations_demandes_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignations_demandes_echeance'), ['echeance'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignations_demandes_statut'), ['statut'], unique=False)

    op.create_table('certifications_securite',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('nom_certification', sa.String(length=255), nullable=False),
    sa.Column('organisme_certificateur', sa.String(length=255), nullable=True),
    sa.Column('date_obtention', sa.Date(), nullable=True),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('numero_certificat', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conformite_administrative',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('connaissance_loi_2013', sa.Boolean(), nullable=True),
    sa.Column('declaration_artci', sa.Boolean(), nullable=True),
    sa.Column('numero_declaration', sa.String(length=100), nullable=True),
    sa.Column('date_declaration', sa.Date(), nullable=True),
    sa.Column('autorisation_artci', sa.Boolean(), nullable=True),
    sa.Column('numero_autorisation', sa.String(length=100), nullable=True),
    sa.Column('date_autorisation', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandes_rapprochement',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('compte_entreprise_id', sa.String(length=36), nullable=False),
    sa.Column('email_demandeur', sa.String(length=255), nullable=False),
    sa.Column('numero_cc', sa.String(length=50), nullable=True),
    sa.Column('document_preuve_path', sa.String(length=500), nullable=True),
    sa.Column('raison_demande', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('en_attente', 'approuve', 'rejete', name='statut_rapprochement_enum'), nullable=False),
    sa.Column('traite_par', sa.String(length=36), nullable=True),
    sa.Column('date_traitement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commentaire_artci', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['compte_entreprise_id'], ['comptes_entreprises.id'], ),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.ForeignKeyConstraint(['traite_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demandes_rapprochement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demandes_rapprochement_statut'), ['statut'], unique=False)

    op.create_table('documents_joints',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('type_document', sa.Enum('cni', 'registre_commerce', 'statuts', 'attestation_fiscale', 'rapport_activite', 'autre', name='type_document_enum'), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploadedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents_joints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_joints_entite_id'), ['entite_id'], unique=False)

    op.create_table('dpo',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Enum('interne', 'externe', name='type_dpo_dpo_enum'), nullable=False),
    sa.Column('organisme', sa.String(length=255), nullable=True),
    sa.Column('date_designation', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entites_conformite',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('score_conformite', sa.Integer(), nullable=True),
    sa.Column('statut_conformite', sa.Enum('conforme', 'demarche_achevee', 'demarche_en_cours', name='statut_conformite_enum'), nullable=True),
    sa.Column('a_dpo', sa.Boolean(), nullable=True),
    sa.Column('type_dpo', sa.Enum('interne', 'externe', name='type_dpo_enum'), nullable=True),
    sa.Column('effectif_entreprise', sa.String(length=50), nullable=True),
    sa.Column('volume_donnees_traitees', sa.String(length=100), nullable=True),
    sa.Column('delai_mise_en_conformite', sa.Date(), nullable=True),
    sa.CheckConstraint('score_conformite >= 0 AND score_conformite <= 100', name='ck_score_conformite_range'),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('entite_id')
    )
    with op.batch_alter_table('entites_conformite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entites_conformite_statut_conformite'), ['statut_conformite'], unique=False)

    op.create_table('entites_contact',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('responsable_legal_nom', sa.String(length=200), nullable=True),
    sa.Column('responsable_legal_fonction', sa.String(length=200), nullable=True),
    sa.Column('responsable_legal_email', sa.String(length=255), nullable=True),
    sa.Column('responsable_legal_telephone', sa.String(length=20), nullable=True),
    sa.Column('site_web', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('entite_id')
    )
    op.create_table('entites_localisation',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('precision_gps', sa.String(length=50), nullable=True),
    sa.Column('methode_geolocalisation', sa.String(length=100), nullable=True),
    sa.Column('adresse_complete', sa.String(length=500), nullable=True),
    sa.Column('code_postal', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('entite_id')
    )
    op.create_table('entites_workflow',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'brouillon_artci', 'soumis', 'en_verification', 'en_attente_complements', 'conforme', 'conforme_sous_reserve', 'valide', 'rejete', 'publie', name='statut_workflow_enum'), nullable=False),
    sa.Column('numero_autorisation_artci', sa.String(length=100), nullable=True),
    sa.Column('date_soumission', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_validation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_publication', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_rejet', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motif_rejet', sa.Text(), nullable=True),
    sa.Column('createdBy', sa.String(length=36), nullable=True),
    sa.Column('assignedTo', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignedTo'], ['users.id'], ),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('entite_id')
    )
    with op.batch_alter_table('entites_workflow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entites_workflow_assignedTo'), ['assignedTo'], unique=False)
        batch_op.create_index(batch_op.f('ix_entites_workflow_createdBy'), ['createdBy'], unique=False)
        batch_op.create_index(batch_op.f('ix_entites_workflow_statut'), ['statut'], unique=False)

    op.create_table('feedbacks_verification',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('date_feedback', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('commentaires', sa.Text(), nullable=True),
    sa.Column('elements_manquants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delai_fourniture', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finalites_bases_legales',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('finalite', sa.String(length=255), nullable=False),
    sa.Column('base_legale', sa.Enum('consentement', 'contrat', 'obligation_legale', 'interet_vital', 'mission_publique', 'interet_legitime', name='base_legale_enum'), nullable=False),
    sa.Column('pourcentage', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_statuts',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('ancien_statut', sa.String(length=50), nullable=True),
    sa.Column('nouveau_statut', sa.String(length=50), nullable=False),
    sa.Column('date_changement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_par', sa.String(length=36), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.ForeignKeyConstraint(['modifie_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historique_statuts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historique_statuts_date_changement'), ['date_changement'], unique=False)
        batch_op.create_index(batch_op.f('ix_historique_statuts_entite_id'), ['entite_id'], unique=False)

    op.create_table('mesures_securite',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('type_mesure', sa.Enum('technique', 'organisationnelle', 'physique', name='type_mesure_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mise_en_oeuvre', sa.Boolean(), nullable=True),
    sa.Column('date_mise_en_oeuvre', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registre_traitements',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('nom_traitement', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('finalite', sa.Text(), nullable=True),
    sa.Column('base_legale', sa.String(length=255), nullable=True),
    sa.Column('categories_personnes', sa.Text(), nullable=True),
    sa.Column('duree_conservation', sa.String(length=100), nullable=True),
    sa.Column('destinataires', sa.Text(), nullable=True),
    sa.Column('transfert_hors_ci', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renouvellements',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('date_demande', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_expiration_agrement', sa.Date(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('en_attente', 'en_cours', 'approuve', 'rejete', name='statut_renouvellement_enum'), nullable=False),
    sa.Column('traite_par', sa.String(length=36), nullable=True),
    sa.Column('date_traitement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.ForeignKeyConstraint(['traite_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsables_legaux',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=True),
    sa.Column('fonction', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securite_conformite',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('politique_securite', sa.Boolean(), nullable=True),
    sa.Column('responsable_securite', sa.Boolean(), nullable=True),
    sa.Column('analyse_risques', sa.Boolean(), nullable=True),
    sa.Column('plan_continuite', sa.Boolean(), nullable=True),
    sa.Column('notification_violations', sa.Boolean(), nullable=True),
    sa.Column('nombre_violations_12mois', sa.Integer(), nullable=True),
    sa.Column('formation_personnel', sa.Boolean(), nullable=True),
    sa.Column('frequence_formation', sa.String(length=100), nullable=True),
    sa.Column('dernier_audit', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('entite_id')
    )
    op.create_table('sous_traitance',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('nom_sous_traitant', sa.String(length=255), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('type_donnees_partagees', sa.Text(), nullable=True),
    sa.Column('contrat_sous_traitance', sa.Boolean(), nullable=True),
    sa.Column('clauses_protection', sa.Boolean(), nullable=True),
    sa.Column('audit_sous_traitant', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferts_internationaux',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('pays_destination', sa.String(length=100), nullable=False),
    sa.Column('organisme_destinataire', sa.String(length=255), nullable=True),
    sa.Column('base_juridique', sa.String(length=255), nullable=True),
    sa.Column('garanties_appropriees', sa.Text(), nullable=True),
    sa.Column('autorisation_artci', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories_donnees',
    sa.Column('entite_id', sa.String(length=36), nullable=False),
    sa.Column('registre_traitement_id', sa.String(length=36), nullable=True),
    sa.Column('categorie', sa.Enum('identite', 'contact', 'financieres', 'sante', 'biometriques', 'localisation', 'professionnelles', 'sensibles', 'mineurs', 'autre', name='categorie_donnees_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('volume_estime', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entite_id'], ['entites_base.id'], ),
    sa.ForeignKeyConstraint(['registre_traitement_id'], ['registre_traitements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories_donnees')
    op.drop_table('transferts_internationaux')
    op.drop_table('sous_traitance')
    op.drop_table('securite_conformite')
    op.drop_table('responsables_legaux')
    op.drop_table('renouvellements')
    op.drop_table('registre_traitements')
    op.drop_table('mesures_securite')
    with op.batch_alter_table('historique_statuts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historique_statuts_entite_id'))
        batch_op.drop_index(batch_op.f('ix_historique_statuts_date_changement'))

    op.drop_table('historique_statuts')
    op.drop_table('finalites_bases_legales')
    op.drop_table('feedbacks_verification')
    with op.batch_alter_table('entites_workflow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entites_workflow_statut'))
        batch_op.drop_index(batch_op.f('ix_entites_workflow_createdBy'))
        batch_op.drop_index(batch_op.f('ix_entites_workflow_assignedTo'))

    op.drop_table('entites_workflow')
    op.drop_table('entites_localisation')
    op.drop_table('entites_contact')
    with op.batch_alter_table('entites_conformite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entites_conformite_statut_conformite'))

    op.drop_table('entites_conformite')
    op.drop_table('dpo')
    with op.batch_alter_table('documents_joints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_joints_entite_id'))

    op.drop_table('documents_joints')
    with op.batch_alter_table('demandes_rapprochement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demandes_rapprochement_statut'))

    op.drop_table('demandes_rapprochement')
    op.drop_table('conformite_administrative')
    op.drop_table('certifications_securite')
    with op.batch_alter_table('assignations_demandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignations_demandes_statut'))
        batch_op.drop_index(batch_op.f('ix_assignations_demandes_echeance'))
        batch_op.drop_index(batch_op.f('ix_assignations_demandes_agent_id'))
        batch_op.drop_index('ix_assign_agent_statut')

    op.drop_table('assignations_demandes')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_compte_type_used')
        batch_op.drop_index(batch_op.f('ix_otp_codes_expires_at'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_compte_entreprise_id'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_code'))

    op.drop_table('otp_codes')
    with op.batch_alter_table('entites_base', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entites_base_ville'))
        batch_op.drop_index(batch_op.f('ix_entites_base_secteur_activite'))
        batch_op.drop_index(batch_op.f('ix_entites_base_region'))
        batch_op.drop_index(batch_op.f('ix_entites_base_publie_sur_carte'))
        batch_op.drop_index(batch_op.f('ix_entites_base_denomination'))
        batch_op.drop_index(batch_op.f('ix_entites_base_compte_entreprise_id'))

    op.drop_table('entites_base')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('comptes_entreprises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comptes_entreprises_email'))

    op.drop_table('comptes_entreprises')
    # ### end Alembic commands ###
